import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import { renderEmail, escapeHtml } from '../lib/emailLayout.js';

/**
 * One layout for every email. What matters: user text can never inject
 * markup, the button carries the right link, the templates in docs/ are
 * generated (not hand-edited) and still hold Supabase's placeholders.
 */

test('renders heading, body, button and footer with the brand', () => {
  const html = renderEmail({
    heading: 'Reset your password',
    paragraphs: ['Click below.'],
    cta: { label: 'Choose a new password', url: 'https://praelecta.ca/reset?x=1&y=2' },
    footnote: 'Ignore if not you.',
    preheader: 'Preview line',
  });
  assert.match(html, /<h1[^>]*>Reset your password<\/h1>/);
  assert.match(html, /href="https:\/\/praelecta\.ca\/reset\?x=1&amp;y=2"/);
  assert.match(html, /Choose a new password/);
  assert.match(html, /logo-mark\.png/);
  assert.match(html, /help@praelecta\.ca/);
  assert.match(html, /Preview line/);
  assert.doesNotMatch(html, /<script/i);
});

test('user-controlled text cannot inject markup', () => {
  const evil = '<img src=x onerror=alert(1)>';
  const html = renderEmail({ heading: evil, paragraphs: [escapeHtml(evil)], cta: { label: evil, url: 'javascript:alert(1)' } });
  assert.doesNotMatch(html, /<img src=x/);
  assert.match(html, /&lt;img src=x/);
});

test('Supabase templates are generated from the layout and keep their placeholders', () => {
  const dir = new URL('../../docs/email-templates/', import.meta.url);
  for (const name of ['confirmation', 'recovery', 'magic_link', 'email_change']) {
    const html = fs.readFileSync(new URL(`${name}.html`, dir), 'utf8');
    assert.match(html, /Generated by scripts\/build-email-templates\.mjs/, `${name} must be generated`);
    assert.match(html, /href="\{\{ \.ConfirmationURL \}\}"/, `${name} must link ConfirmationURL unescaped`);
    assert.match(html, /logo-mark\.png/);
    assert.doesNotMatch(html, /\{\{ \.ConfirmationURL \}\}&/, 'placeholder must not be HTML-escaped');
  }
  assert.match(fs.readFileSync(new URL('email_change.html', dir), 'utf8'), /\{\{ \.NewEmail \}\}/);
});

test('the README lists every generated template with its subject', () => {
  const readme = fs.readFileSync(new URL('../../docs/email-templates/README.md', import.meta.url), 'utf8');
  for (const f of ['confirmation.html', 'recovery.html', 'magic_link.html', 'email_change.html']) assert.match(readme, new RegExp(f));
});
