import React, { useState, useEffect } from 'react';
import { base44 } from '@/api/base44Client';
import { userStorageKey } from '@/lib/currentUser';
import { Printer, X, Loader2 } from 'lucide-react';

export default function AutoPrintPrompt() {
  const [todaysLectures, setTodaysLectures] = useState([]);
  const [checking, setChecking] = useState(true);
  const [dismissed, setDismissed] = useState(false);
  const [printing, setPrinting] = useState(false);

  useEffect(() => {
    const storageKey = userStorageKey('autoprint-dismissed');
    const dismissedDate = storageKey ? localStorage.getItem(storageKey) : null;
    const today = new Date().toISOString().split('T')[0];
    if (dismissedDate === today) {
      setDismissed(true);
      setChecking(false);
      return;
    }

    const checkTodaysLectures = async () => {
      try {
        const today = new Date().toISOString().split('T')[0];
        const lecs = await base44.entities.Lecture.filter({ date: today }, '-created_date');
        const withTranscripts = lecs.filter(l => l.transcript && l.transcript.length > 50 && l.status === 'complete');
        setTodaysLectures(withTranscripts);
      } catch (e) { /* skip */ }
      setChecking(false);
    };
    checkTodaysLectures();
  }, []);

  const dismiss = () => {
    const today = new Date().toISOString().split('T')[0];
    const storageKey = userStorageKey('autoprint-dismissed');
    if (storageKey) localStorage.setItem(storageKey, today);
    setDismissed(true);
  };

  const handlePrintAll = async () => {
    setPrinting(true);
    try {
      const htmlParts = [];
      for (const lec of todaysLectures) {
        const res = await base44.functions.invoke('exportTranscript', {
          lecture_id: lec.id,
          mode: 'print',
        });
        if (res.data?.html) {
          // Extract body content
          const bodyMatch = res.data.html.match(/<body[^>]*>([\s\S]*?)<\/body>/i);
          htmlParts.push(bodyMatch ? bodyMatch[1] : res.data.html);
        }
      }

      const combinedHtml = `<!DOCTYPE html><html><head><meta charset="utf-8"><title>Today's Lectures — ${new Date().toLocaleDateString()}</title>
<style>
  @page { margin: 1in; }
  body { font-family: Georgia, 'Times New Roman', serif; line-height: 1.7; color: #1a1a1a; max-width: 700px; margin: 0 auto; }
  .header { border-bottom: 2px solid #2E66FF; padding-bottom: 16px; margin-bottom: 24px; }
  .header h1 { font-size: 20px; margin: 0 0 8px 0; }
  .meta { font-size: 13px; color: #555; display: flex; flex-wrap: wrap; gap: 16px; }
  .meta strong { color: #1a1a1a; }
  .section-label { font-size: 11px; text-transform: uppercase; letter-spacing: 0.05em; color: #2E66FF; font-weight: 600; margin-bottom: 6px; }
  .summary { background: #f8f9ff; border-left: 3px solid #2E66FF; padding: 12px 16px; margin-bottom: 24px; font-size: 14px; }
  .transcript { font-size: 14px; white-space: pre-wrap; word-wrap: break-word; }
  .concepts { display: flex; flex-wrap: wrap; gap: 8px; margin-bottom: 24px; }
  .concept-tag { background: #eef2ff; color: #2E66FF; padding: 4px 10px; border-radius: 4px; font-size: 12px; font-family: sans-serif; }
  .lecture-divider { page-break-before: always; border-top: 3px dashed #ddd; margin-top: 48px; padding-top: 24px; }
  .footer { margin-top: 32px; border-top: 1px solid #ddd; padding-top: 12px; font-size: 11px; color: #999; text-align: center; }
</style></head><body>
<h1 style="font-size: 24px; color: #2E66FF; margin-bottom: 4px;">Today's Lectures</h1>
<p style="color: #666; font-size: 14px; margin-bottom: 32px;">${new Date().toLocaleDateString('en-US', { weekday: 'long', year: 'numeric', month: 'long', day: 'numeric' })}</p>
${htmlParts.map((h, i) => `<div class="${i > 0 ? 'lecture-divider' : ''}">${h}</div>`).join('')}
<div class="footer">Generated by Cedar Student Pilot — ${new Date().toLocaleDateString()}</div>
</body></html>`;

      const printWin = window.open('', '_blank');
      if (!printWin) {
        alert('Please allow pop-ups to print transcripts.');
        return;
      }
      printWin.document.write(combinedHtml);
      printWin.document.close();
      printWin.focus();
      setTimeout(() => printWin.print(), 500);
      dismiss();
    } catch (e) {
      alert('Could not prepare transcripts for printing.');
    }
    setPrinting(false);
  };

  if (checking || dismissed || todaysLectures.length === 0) return null;

  return (
    <div className="mb-4 rounded-xl border border-primary/30 bg-primary/5 p-3 flex items-center gap-3 animate-fade-in">
      <div className="w-9 h-9 rounded-lg bg-primary/10 flex items-center justify-center flex-shrink-0">
        <Printer className="w-4 h-4 text-primary" />
      </div>
      <div className="flex-1 min-w-0">
        <p className="text-sm font-semibold text-foreground">Print today's transcripts?</p>
        <p className="text-xs text-muted-foreground">
          {todaysLectures.length} lecture{todaysLectures.length !== 1 ? 's' : ''} from today ready to print
        </p>
      </div>
      <button
        onClick={handlePrintAll}
        disabled={printing}
        className="inline-flex items-center gap-1.5 px-3 py-2 rounded-lg bg-primary text-primary-foreground text-xs font-medium hover:bg-primary/90 disabled:opacity-50 flex-shrink-0"
      >
        {printing ? <Loader2 className="w-3.5 h-3.5 animate-spin" /> : <Printer className="w-3.5 h-3.5" />}
        Print All
      </button>
      <button onClick={dismiss} className="text-muted-foreground hover:text-foreground flex-shrink-0">
        <X className="w-4 h-4" />
      </button>
    </div>
  );
}