-- Reconstructed academic entity graph. Compatibility timestamps are added by
-- the later migration recorded for that purpose.
create table public.semesters (id uuid primary key default gen_random_uuid(),user_id uuid not null references auth.users(id) on delete cascade,name text not null,start_date date not null,end_date date not null,is_active boolean not null default false);
create table public.classes (id uuid primary key default gen_random_uuid(),user_id uuid not null references auth.users(id) on delete cascade,semester_id uuid not null references public.semesters(id) on delete cascade,name text not null,instructor text,room text,color text not null default '#3B82F6',days_of_week text[] not null default '{}',start_time text,end_time text);
create table public.lectures (id uuid primary key default gen_random_uuid(),user_id uuid not null references auth.users(id) on delete cascade,class_id uuid not null references public.classes(id) on delete cascade,date date not null,recording_url text,duration_seconds numeric,transcript text,ai_title text,ai_summary text,ai_concepts text[] not null default '{}',ai_vocabulary text[] not null default '{}',ai_definitions jsonb not null default '[]',ai_formulas text[] not null default '{}',ai_action_items text[] not null default '{}',ai_exam_mentions text[] not null default '{}',is_missed boolean not null default false,status text not null default 'pending' check(status in ('pending','processing','complete')));
create table public.assignments (id uuid primary key default gen_random_uuid(),user_id uuid not null references auth.users(id) on delete cascade,class_id uuid not null references public.classes(id) on delete cascade,title text not null,due_date date not null,type text not null default 'assignment' check(type in ('exam','quiz','project','assignment')),status text not null default 'active' check(status in ('active','completed','archived')),coverage_scope text not null default 'cumulative' check(coverage_scope in ('cumulative','since_last','custom')),lecture_range_start text,lecture_range_end text,description text,project_metadata jsonb not null default '{}',roadmap jsonb not null default '[]');
create table public.notes (id uuid primary key default gen_random_uuid(),user_id uuid not null references auth.users(id) on delete cascade,lecture_id uuid references public.lectures(id) on delete cascade,class_id uuid not null references public.classes(id) on delete cascade,content text,attachments text[] not null default '{}');
create table public.study_sessions (id uuid primary key default gen_random_uuid(),user_id uuid not null references auth.users(id) on delete cascade,assignment_id uuid references public.assignments(id) on delete cascade,class_id uuid not null references public.classes(id) on delete cascade,scheduled_date date not null,scheduled_time text,duration_minutes numeric,priority text not null default 'medium' check(priority in ('high','medium','low')),status text not null default 'scheduled' check(status in ('scheduled','completed','skipped')),title text,notes text,email_notified boolean not null default false,session_type text not null default 'study' check(session_type in ('study','project')),roadmap_step_index numeric);
create table public.study_records (id uuid primary key default gen_random_uuid(),user_id uuid not null references auth.users(id) on delete cascade,duration_seconds numeric not null,date date not null,class_id uuid references public.classes(id) on delete cascade,mode text check(mode in ('pomodoro','simple')),cycles_completed numeric,goal_minutes numeric,study_type text not null default 'manual' check(study_type in ('in_app','manual')),study_mode text check(study_mode in ('deep','sprint','review')),lectures_covered numeric not null default 0,total_lectures numeric not null default 0,quiz_score numeric,quiz_questions_count numeric,topics_reviewed text[] not null default '{}');
create table public.calendar_events (id uuid primary key default gen_random_uuid(),user_id uuid not null references auth.users(id) on delete cascade,title text not null,date date not null,start_time text,end_time text,type text not null default 'custom' check(type in ('class','custom','study','work','appointment','reminder')),color text not null default '#3B82F6',notes text,reminder_minutes_before numeric,class_id uuid references public.classes(id) on delete cascade);
create table public.class_attendance (id uuid primary key default gen_random_uuid(),user_id uuid not null references auth.users(id) on delete cascade,class_id uuid not null references public.classes(id) on delete cascade,date date not null,attended boolean not null default false,confirmed_at timestamptz);
create table public.knowledge_coverage (id uuid primary key default gen_random_uuid(),user_id uuid not null references auth.users(id) on delete cascade,class_id uuid not null references public.classes(id) on delete cascade,lecture_id uuid references public.lectures(id) on delete cascade,concepts_seen text[] not null default '{}',concepts_mastered text[] not null default '{}',proficiency numeric not null default 0,sessions_reviewed numeric not null default 0,last_reviewed_date date);
create table public.flashcards (id uuid primary key default gen_random_uuid(),user_id uuid not null references auth.users(id) on delete cascade,lecture_id uuid references public.lectures(id) on delete cascade,class_id uuid not null references public.classes(id) on delete cascade,front text not null,back text not null,ai_generated boolean not null default true);
create table public.practice_questions (id uuid primary key default gen_random_uuid(),user_id uuid not null references auth.users(id) on delete cascade,lecture_id uuid references public.lectures(id) on delete cascade,class_id uuid not null references public.classes(id) on delete cascade,question text not null,answer text not null,options text[] not null default '{}',type text not null default 'multiple_choice' check(type in ('multiple_choice','short_answer')),ai_generated boolean not null default true);
create table public.study_session_reviews (id uuid primary key default gen_random_uuid(),user_id uuid not null references auth.users(id) on delete cascade,study_record_id uuid references public.study_records(id) on delete cascade,class_id uuid not null references public.classes(id) on delete cascade,lecture_ids uuid[] not null default '{}',ai_interactions jsonb not null default '[]',review_questions jsonb not null default '[]',self_assessment jsonb not null default '[]',proficiency_score numeric,coverage_percentage numeric,in_depth_score numeric,overall_score numeric);
create table public.custom_tracks (id uuid primary key default gen_random_uuid(),user_id uuid not null references auth.users(id) on delete cascade,title text not null,video_id text not null);
create table public.handbooks (id uuid primary key default gen_random_uuid(),user_id uuid not null references auth.users(id) on delete cascade,class_id uuid not null references public.classes(id) on delete cascade,scope_key text not null,source_hash text not null,payload text not null,total_lectures numeric not null default 0,generated_at timestamptz not null default now());
create index assignments_class_idx on public.assignments(class_id); create index calendar_events_user_idx on public.calendar_events(user_id); create index classes_semester_idx on public.classes(semester_id); create index classes_user_idx on public.classes(user_id); create index flashcards_class_idx on public.flashcards(class_id); create index handbooks_class_idx on public.handbooks(class_id); create unique index handbooks_class_scope_idx on public.handbooks(class_id,scope_key); create index knowledge_coverage_class_idx on public.knowledge_coverage(class_id); create index lectures_class_idx on public.lectures(class_id); create index lectures_user_idx on public.lectures(user_id); create index notes_class_idx on public.notes(class_id); create index practice_questions_class_idx on public.practice_questions(class_id); create index study_sessions_assignment_idx on public.study_sessions(assignment_id); create index study_sessions_class_idx on public.study_sessions(class_id);
do $$ declare table_name text; begin foreach table_name in array array['assignments','calendar_events','class_attendance','classes','custom_tracks','flashcards','knowledge_coverage','lectures','notes','practice_questions','semesters','study_records','study_session_reviews','study_sessions'] loop execute format('alter table public.%I enable row level security',table_name); execute format('grant select,insert,update,delete on public.%I to authenticated',table_name); execute format('grant all on public.%I to service_role',table_name); execute format('create policy "owner all" on public.%I for all to authenticated using ((select auth.uid())=user_id) with check ((select auth.uid())=user_id)',table_name); end loop; end $$;
alter table public.handbooks enable row level security;
create policy "select own handbooks" on public.handbooks for select to authenticated using ((select auth.uid())=user_id);
grant select on public.handbooks to authenticated; grant all on public.handbooks to service_role;
